Prevents snapshots if there are no creators.
seek4science/seek pull request #1592
Opened 2023-09-20 10:32 UTC by fherreazcue

This avoids issues with DOI generation.

2023-09-20 16:00 UTC, fbacall requested changes
Looks good, just a few minor tweaks needed

2023-09-20 16:18 UTC, fherreazcue commented on test/functional/snapshots_controller_test.rb
> +      request.path = Seek::Util.routes.polymorphic_path(snap)+"/snapshots"
Resolved in [4e2740d](https://github.com/seek4science/seek/pull/1592/commits/4e2740d049bdf4df625f433f2fc0a4ccf696384d).

2023-09-20 16:18 UTC, fherreazcue commented on lib/seek/research_objects/acts_as_snapshottable.rb
> +            errors.add(:base, "At least one creator is required. To add, go to Actions -> Manage #{self.class.name}.")
Resolved in [4e2740d](https://github.com/seek4science/seek/pull/1592/commits/4e2740d049bdf4df625f433f2fc0a4ccf696384d).

2023-09-28 14:22 UTC, stuzart approved these changes

2023-09-28 14:23 UTC, merged