Import projects from Data Management Plan files
seek4science/seek pull request #1697
Opened 2023-12-13 01:29 UTC by Menjabin

Adds a workflow for importing projects from Data Management Plan files that follow the RDA DMP Common Standard. This format is used by e.g. ELIXIR's Data Stewardship Wizard, and it would greatly simplify the process of publishing projects from there to a SEEK instance if it could be done by a simple file upload rather than by manually entering the data.

This solution reads the data about a project from a DMP file, and this is used to create a new project. All contributors to the project are also read from the file, and user accounts are created and added as members of the newly created project.
The option to import a project is currently only presented to the user on both the "new project" and "guided create" pages. It is not accessible through the main navbar.

2023-12-13 13:47 UTC, stuzart commented
Hi,
There is something wrong with the PR and cannot review or merge. It contains many changes to many files, many of them reverting recent changes. I've tried looking at the commit itself by cloning and checking outside of github - and it is the same there too.
It's possible that resyncing with the latest main branch may solve things, but otherwise it will require a new PR that contains only the changes for the new feature.

2023-12-14 00:07 UTC, Menjabin commented
My apologies,
I have updated the branch so that only my changes remain.

2023-12-15 16:31 UTC, stuzart requested changes
it lacks any functional or unit tests, and due to being quite complex and involved it really needs.
Without them it is difficult to review the pull request works, and also there is high potential for things to break without knowing with future changes

2023-12-25 12:17 UTC, Menjabin commented
I have now added tests for the new functionality

2024-01-11 10:07 UTC, stuzart approved these changes

2024-01-11 10:11 UTC, kdp-cloud approved these changes
There's a missing indentation in `routes.rb` on line 745.
Other than that, no comments!

2024-01-11 10:11 UTC, kdp-cloud commented on config/routes.rb
> +post :filter_isa_tags_by_level
Missing indentation?

2024-01-11 10:12 UTC, stuzart commented on config/routes.rb
> +post :filter_isa_tags_by_level
we can fix that after it's merged

2024-01-11 10:12 UTC, merged

2024-01-11 10:13 UTC, stuzart commented
thanks for the contribution!