Issue 1737 fix isa tags in sample types
seek4science/seek pull request #1749
Opened 2024-02-12 15:56 UTC by kdp-cloud

- Make sample type attributes editable, based on whether they're inherited.
- Make template attributes editable, based on whether they're inherited.

2024-02-15 10:26 UTC, stuzart requested changes
the inheritance between template attributes as parents to other attribute and sample attributes is a bit confusing. And I'm confused why, as Template also have parents and children. Could the relationship between the attributes not be determined through the parent Template ? Or can attributes from different Templates and SampleTypes have parent/child relationships - which sounds like a nightmare.

There also seems to be danger of parent attributes being deleted, but there children left dangling - not the case for templates as there is a check on can_delete?

2024-02-15 10:26 UTC, stuzart commented on app/models/template_attribute.rb
> +    !parent_attribute_id.nil?
would be better to do `parent_attribute.present?` - to handle where the parent id no longer exists, and also looks cleaner

2024-02-15 10:26 UTC, stuzart commented on app/views/sample_types/_sample_attribute_form.html.erb
> +<% allow_isa_tag_change = constraints.allow_isa_tag_change?(sample_attribute) %>
aren't all these database queries and overheads only necessary if display_isa_tag is true ?

2024-02-15 10:26 UTC, stuzart commented on lib/seek/samples/sample_type_editing_constraints.rb
> +      def inherrited?(attr)
misspelling, also could this not be a method and question to the sample attribute? `.inherited_from_template_attribute?`

2024-02-15 10:26 UTC, stuzart commented on lib/seek/samples/sample_type_editing_constraints.rb
> +        attr&.template_attribute_id?
would be safer to do `attr&.template_attribute.present?`

2024-02-16 12:55 UTC, kdp-cloud commented
Thank you for reviewing and sharing your concerns. I will try to provide a bit of context to why certain choices were made.

Your first question about links between both template attributes and sample attributes comes down to this: I need to know whether a template/sample attribute is inherited from a template or not. We want to prohibit users to edit the ISA tag of a template/sample attribute, when it is inherited. To me it seemed that the best way to achieve this, was by linking the parent attribute and child attribute through a foreign key. If there is a simpler way to achieve the same thing by not making DB changes, please let me know.

Templates have both parents and children because we encourage users to create new templates by starting from existing templates and editing them. This takes away the burden of knowing which ISA tag you need to link to which attribute. The idea of preserving a link between parent and children is meant as a first step towards advanced querying samples through templates. But this feature is not developed yet.

As for deleting parents, it is currently prohibited to delete a template when it has sample types or child templates linked to it. The button should be hidden and there is a clause in the `can_delete?` method to prevent from deleting templates.

In the meantime, I made the changes your requested.

2024-02-19 14:03 UTC, stuzart approved these changes

2024-02-21 12:03 UTC, merged