Sanitize objects input dynamic table
seek4science/seek pull request #1857
Opened 2024-04-24 15:25 UTC by kdp-cloud

Fix for XSS vulnerability in dynamic table in multiple places.

2024-05-01 07:18 UTC, kdp-cloud commented
HTML tags in sample attribute values are escaped now.
![image](https://github.com/seek4science/seek/assets/82407142/43efcb5b-b764-4004-8918-c7e320c45a55)

2024-05-01 09:51 UTC, stuzart requested changes
minor changes

2024-05-01 09:51 UTC, stuzart commented on app/helpers/dynamic_table_helper.rb
> +        is_cv_list = a.sample_attribute_type.base_type == Seek::Samples::BaseType::CV_LIST
you can use `sample_attribute_type.seek_cv_list?`

2024-05-01 09:51 UTC, stuzart commented on app/assets/javascripts/single_page/dynamic_table.js.erb
> +        const extraClass = '';
could `sanitizeData(e)` be called once at the start and assigned to a variable, instead of being called repeatedly?

2024-05-01 17:04 UTC, stuzart commented on app/assets/javascripts/single_page/dynamic_table.js.erb
> +        const extraClass = '';
looking at it again, I can see that e may be different in each case, so ignore this

2024-05-02 14:03 UTC, stuzart approved these changes

2024-05-02 14:04 UTC, merged