Additions to the observation unit UI
seek4science/seek pull request #1975
Opened 2024-08-21 11:56 UTC by stuzart

Consolidated earlier changes with those done by PhenomUK.
Added ability to associate a data file or sample

* Fix for #1961

2024-08-22 16:50 UTC, AndrewWood94 requested changes
Minor changes needed on new Obs Unit file, otherwise all good

2024-08-22 16:50 UTC, AndrewWood94 commented on app/views/observation_units/new.html.erb
Text for no Investigation/Study available is still referencing Assay no Obs Unit

2024-08-23 10:27 UTC, stuzart commented on app/views/observation_units/new.html.erb
good spot

2024-08-23 11:35 UTC, merged

2024-08-23 11:35 UTC, stuzart commented
> Minor changes needed on new Obs Unit file, otherwise all good

Thanks. I fixed the error and based on this comment gone straight ahead and merged